language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TARGET=phpunit_run

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_REQUIRE=3.4.* REMOVE_FOS=1
    - php: 7.4
      env: SYMFONY_REQUIRE=3.4.* REMOVE_FOS=1
    - php: 7.2
      env: SYMFONY_REQUIRE=4.4.* REMOVE_FOS=1
    - php: 7.4
      env: SYMFONY_REQUIRE=4.4.* REMOVE_FOS=1
    - php: 7.4
      env: SYMFONY_REQUIRE=5.0.* REMOVE_FOS=1
    - php: 7.3
      env: SYMFONY_REQUIRE=5.0.* REMOVE_FOS=1
    - php: 7.4
      env: TARGET=csfixer_dry_run

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available";
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

before_script:
  - if [[ ${REMOVE_FOS} ]]; then composer remove friendsofsymfony/user-bundle --no-update --no-interaction --dev; fi;
  - composer install --prefer-dist --no-interaction --no-scripts

script:
  - make $TARGET
