language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION='2.1.*' FOSUSERBUNDLE_VERSION='~1.2'
  - SYMFONY_VERSION='2.2.*' FOSUSERBUNDLE_VERSION='~1.2'
  - SYMFONY_VERSION='2.3.*' FOSUSERBUNDLE_VERSION='~1.2'
  - SYMFONY_VERSION='2.1.*' FOSUSERBUNDLE_VERSION='2.0.*@dev'
  - SYMFONY_VERSION='2.2.*' FOSUSERBUNDLE_VERSION='2.0.*@dev'
  - SYMFONY_VERSION='2.3.*' FOSUSERBUNDLE_VERSION='2.0.*@dev'

before_script:
    - composer require --no-update symfony/symfony=${SYMFONY_VERSION}
    - composer require --no-update friendsofsymfony/user-bundle=${FOSUSERBUNDLE_VERSION}
    - composer install --prefer-source
