language: php

php:
  - 5.3
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION="3.0.x-dev as 2.8"
    - php: 5.6
      env: FOSUSERBUNDLE_VERSION=1.3.*
    - php: 5.6
      env: FOSUSERBUNDLE_VERSION=2.0.*@dev
    - php: hhvm
  allow_failures:
    - env: SYMFONY_VERSION="3.0.x-dev as 2.8"

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$FOSUSERBUNDLE_VERSION" != "" ]; then composer require "friendsofsymfony/user-bundle:${FOSUSERBUNDLE_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: phpunit
